server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/qiaodaimadewangcai/tensquare-dev.git
  rabbitmq:
    host: 192.168.44.130
  managerment:
    endpoints:
      web:
        exposure:
          include: bus-refresh